# Generated by Django 4.0.3 on 2022-03-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prec_producto', models.CharField(max_length=40)),
                ('prec_instalacion', models.IntegerField()),
                ('cliente', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('valor_producto', models.IntegerField()),
                ('precio_producto', models.IntegerField()),
            ],
        ),
    ]
