# Generated by Django 4.0.3 on 2022-03-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='direccion',
        ),
    ]
