# Generated by Django 4.0.3 on 2022-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_App', '0002_remove_pedidos_fecha_remove_trabajos_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='producto',
            field=models.TextField(max_length=40),
        ),
    ]
