# Generated by Django 4.0.3 on 2022-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_App', '0003_alter_pedidos_cliente_alter_pedidos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajos',
            old_name='prec_producto',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='trabajos',
            old_name='prec_instalacion',
            new_name='precio_instalacion',
        ),
    ]
