# Generated by Django 4.0.3 on 2022-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_App', '0004_rename_prec_producto_trabajos_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='producto',
            field=models.CharField(max_length=40),
        ),
    ]
